jespersite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from mainapp.views import *
from jespersite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    #список URL адресов mainapp
    path('', include('mainapp.urls')), 
]

#в режиме отладки добавление ещё одного маршрута для медиа файлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#ссылка на функцию обработчик страницы 404
handler404 = PageNotFound


mainapp/urls.py
from django.urls import path, include
from django.conf.urls import *

from .views import *

#name - имя страницы (неявный url адрес)
#as_view() - вызов ф. связи класса с маршрутом
#social-auth/ url шаблон для авторизации через социальные сети
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('economy/', economy.as_view(), name='economy'),
    path('dev/', dev.as_view(), name='dev'),
    path('life/', life.as_view(), name='life'),
    path('logout/', logout_user, name='logout'),
    path('<slug:section_slug>/article/<slug:post_slug>/', ShowArticle.as_view(), name='article'),
    path('page/<slug:username>/', userpage.as_view(), name='user-page'),
    path('page/<slug:username>/settings', userpagesettings.as_view(), name='user-page-set'),
    path('adminpanel/<slug:username>/', adminpanel.as_view(), name=""),
    path('account/active/<uidb64>/<token>/', EmailVerify.as_view(), name='userverify'),
    path('account/reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='userpasswordreset'),
    path('social-auth/', include('social_django.urls', namespace='social')),

]

mainapp/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils.translation import gettext_lazy as _

from .utils import user_directory_path, correct_email
from mptt.models import MPTTModel, TreeForeignKey
from uuslug import uuslug, slugify

class CustomAccountManager(BaseUserManager):
   def create_user(self, email, username, password=None, **other_fields):
      if not email:
         email = username + '@telegram.com'
         #raise ValueError(_('Please provide an email address'))
      user=self.model(username=username, email=correct_email(email), **other_fields)
      user.set_password(password)
      user.save()
      return user

   def create_superuser(self, email, username, password, **other_fields):
      other_fields.setdefault('is_staff',True)
      other_fields.setdefault('is_superuser',True)
      other_fields.setdefault('is_active',True)
      if other_fields.get('is_staff') is not True:
         raise ValueError(_('Please assign is_staff=True for superuser'))
      if other_fields.get('is_superuser') is not True:
         raise ValueError(_('Please assign is_superuser=True for superuser'))
      return self.create_user(email, username, password, **other_fields)

     
class MyUser(AbstractBaseUser, PermissionsMixin):
   email = models.EmailField(_('Email'), unique=True)
   username= models.CharField(_('UserName'), max_length=25, db_index=True)
   first_name = models.CharField(_('First Name'), max_length=25, blank=True)
   last_name = models.CharField(_('Last Name'), max_length=25, blank=True)
   is_staff = models.BooleanField(_('Is staff'), default=False)
   is_active = models.BooleanField(_('Is active'), default=True)
   
   id = models.AutoField(primary_key=True)
   userslug = models.SlugField(max_length=150, unique=True, db_index=True, verbose_name='UserSlug')
   userpic = models.ImageField(upload_to=user_directory_path, blank=True, verbose_name='Аватар', default='baseuserpic.jpg' )
   theme = models.ImageField(upload_to=user_directory_path, blank=True, verbose_name='Фон')
   description = models.CharField(max_length=150, blank=True, verbose_name='Пару слов о себе')
   date_joined = models.DateTimeField(_("date joined"), blank=True, null=True, auto_now_add=True)
   email_verify = models.BooleanField(_('Verified email'), default=False)

   objects = CustomAccountManager()
   
   USERNAME_FIELD='email' #the name of the field on the user model that is used as the unique identifier
   REQUIRED_FIELDS=['username'] # запрашиваемое поле при вызове createsuperuser

   def __str__(self):
      return self.email
    
   def save(self, *args, **kwargs):
      if self.is_superuser:                                                               #slug for superuser                                      
         self.userslug = self.username.lower().replace(' ', '-')
      try:
         super(MyUser, self).save(*args, **kwargs)
      except:
         raise ValueError(_('This admin already exists!'))
      self.update_user_slug() 
      
   def update_user_slug(self):
      # You now have both access to self.id
      if not self.is_superuser: 
         #now have both access to self.id
         self.userslug = str(self.id) + '-' + slugify(self.username.lower().replace(' ', '-')) #slug for user
         MyUser.objects.filter(id=self.id).update(userslug=self.userslug)
         
   def get_absolute_url(self):
        return reverse('user-page', args=[self.userslug])
     
   class Meta:
      verbose_name = 'Пользователь'
      verbose_name_plural = 'Пользователи'
      
      
#хранение контента
class articles(models.Model):
   SECTIONS = [('economy', 'Экономика'), ('dev', 'Разработка | IT'), ('life', 'Жизнь')]
   section = models.CharField(max_length=15, choices=SECTIONS)
   title = models.CharField(max_length=150, verbose_name='Заголовок')
   slug = models.SlugField(max_length=1001, unique=True, db_index=True, verbose_name='URL')
   subtitle = models.CharField(max_length=350, verbose_name='Подзаголовок', blank=True)
   #many articles to one user
   author = models.ForeignKey(MyUser, on_delete=models.CASCADE, verbose_name='Автор')
   text = models.TextField(blank=True, verbose_name='Текст')
   time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
   is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
   content = models.FileField(upload_to='files/%Y/%m/%d', blank=True, validators=[
      FileExtensionValidator(
         allowed_extensions=['jpg', 'png', 'mp4', 'gif', 'mov', 'heic'], 
         message='Некорректный формат файла!',
         )
      ])
   
   #формирование маршрута к конкретной записи
   def get_absolute_url(self):
      # 'article' - имя маршрута в urls.py
      return reverse("article", kwargs={"post_slug": self.slug,"section_slug": self.section})
   
   def __unicode__(self):
      return self.title

   #транслитерация слага
   def save(self, *args, **kwargs):
      self.slug = uuslug(self.title, instance=self)
      super(articles, self).save(*args, **kwargs) 
      
   #тип файла
   def get_file_type(self):
      a = self.content.name.find('.') + 1
      if self.content.name[a:] in ['jpg', 'png', 'heic']: return 'photo'
      elif self.content.name[a:] in  ['mp4', 'mov', 'heic']: return 'video'
   
   #метод для отображения объекта
   def __str__(self):
      return self.title
   
   #вложенный класс для настройки админ панели
   class Meta:
      verbose_name = 'Статьи'
      verbose_name_plural = 'Статьи'
      #сортировка отображения статей
      ordering = ['time_create']
   
   
class comments(MPTTModel):
   # через related_name обращаемся к множеству объектов класса comments, связанных с объектом класса articles
   post = models.ForeignKey(articles, on_delete=models.CASCADE, related_name='cmnts', verbose_name='Статья')
   author = models.ForeignKey(MyUser, on_delete=models.DO_NOTHING, verbose_name='Автор комментария')
   text = models.TextField(verbose_name='Текст комментария')
   time_create = models.DateTimeField(auto_now_add=True)
   is_active = models.BooleanField(default=True, verbose_name='Опубликовано')
   #many answers to one parent comment (tree, data structure)
   parent = TreeForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, related_name='children', db_index=True, verbose_name='Род.Коммент')
   
   class Meta:
      verbose_name = 'Комментарии'
      verbose_name_plural = 'Комментарии'
      ordering = ['time_create']
      
   #метод для отображения объекта
   def __str__(self):
      return self.text
   
   
class likes(models.Model):
   #many likes to one article
   post = models.ForeignKey(articles, on_delete=models.CASCADE, related_name='likes', verbose_name='Статья')
   like = models.BooleanField(default=False, verbose_name='Лайки')
   liked_by = models.ForeignKey(MyUser, on_delete=models.DO_NOTHING, verbose_name='Автор лайка')
   time_create = models.DateTimeField(auto_now_add=True)
   
   class Meta:
      verbose_name = 'Лайки'
      verbose_name_plural = 'Лайки'
      ordering = ['time_create']
      

mainapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm, SetPasswordForm, UserChangeForm
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model

from .models import *

class AddArticleForm(forms.ModelForm):
   #констуктор для невыбранного значения формы
   def __init__(self, *args, **kwargs):
      super(AddArticleForm, self).__init__(*args, **kwargs)
      #self.fields['section'].empty_label = ' '
      self.fields["section"].choices = [("", ""),] + list(self.fields["section"].choices)[1:]
   
   class Meta:
      #связь формы с моделью
      model = articles
      #отображаемые поля
      fields = ['section', 'author', 'title', 'subtitle', 'text', 'content']
      widgets = {
         'title': forms.TextInput(attrs={"class": "form-input"}),
         'text': forms.Textarea(attrs={"cols": 60, "rows": 10}),
      }
      
class AddCommentForm(forms.ModelForm):
   class Meta:
      model = comments
      fields = ['text']
      widgets = {
         'text': forms.Textarea(attrs={"class": "form-control", "placeholder": "Add your comment here", 
                                       "rows": "3", "cols": "61", "style":"resize:none;", }),
      }
      labels = {
        'text': '',
      }
      
class AddAnswerForm(AddCommentForm):
   
   def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #print(self.fields['parent'])                    
        
   class Meta:
      model = comments
      fields = ['text', 'parent']
      widgets = {
         'text': forms.Textarea(attrs={"class": "cmt-form", "placeholder": "Add your comment here", 
                                       "rows": "3", "cols": "61", "style":"resize:none;",}),
      }
      
      
class UserRegistration(UserCreationForm):
   
   password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={"class": "text-field__input"}))
   password2 = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={"class": "text-field__input"}),)
      
   def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = ''
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''

   def clean(self):
      email = self.cleaned_data.get('email')
      if email is not None and MyUser.objects.filter(email=email.lower()).exists():
         raise ValidationError("Данный Email уже занят!")
      return self.cleaned_data
        
   class Meta(UserCreationForm.Meta):
      model = get_user_model()
      fields = ['email', 'username', 'password1']
      widgets = {'email': forms.TextInput(attrs={"class": "text-field__input"}),
                 'username': forms.TextInput(attrs={"class": "text-field__input"}),
      }
      
class UserAuthentication(AuthenticationForm):
   # email = username
   def clean(self):
      data = self.data.copy()
      data['username'] = data['username'].lower()
      return data
   
class UserPasswordReset(PasswordResetForm):
   pass

class UserPasswordSet(SetPasswordForm):
   pass

class UserChangeCustom(UserChangeForm):
   
   def __init__(self, *args, **kwargs):
      super(UserChangeForm, self).__init__(*args, **kwargs)
      del self.fields['password']
   
   class Meta:
      model = get_user_model()
      fields = ('email', 'username', 'userpic', 'theme', 'description')
      

mainapp/templates/mainapp/addpost.html
<!--user page template-->
{% extends 'mainapp/base.html' %}

{% block content %}
<h1>{{ title }}</h1>

<!--forms test-->
<form action='{% url 'personal-page' %}' method='post' enctype='multipart/form-data'>
   <!--method - метод скрытой передачи данных 
      csrf_token  служит для защенной обработки формы-->
   {% csrf_token %}
   {{ form.as_p }}
   <button type='submit'>Добавить</button>

</form>
{% endblock %}

mainapp/templates/mainapp/article.html
<!--site article template-->
{% extends 'mainapp/base.html' %}
{% load mainapp_tags %}
{% load mptt_tags %}

{% block content %}

{% comment %} 
<div class="container bootstrap snippets bootdey">
   <div class="row justify-content-md-center">
      <div class="col-md-8">
         <div class="col-sm-12">
            <div class="panel panel-white post panel-shadow">
               <div class="post-heading">

                  <!--user avatar--
                  <div class="pull-left image">
                     <a href="{% url 'user-page' post.author.userslug %}">
                        <img src="{{post.author.userpic.url}}" class="img-circle avatar" alt="user profile image">
                     </a>
                  </div>
                  <!--info about creator--
                  <div class="pull-left meta">
                     <div class="title h5">
                        <a href="{% url 'user-page' post.author.userslug %}"><b>{{post.author}}</b></a>
                     </div>
                     <h6 class="text-muted time">{{post.time_create}}</h6>
                  </div>
                      
               </div>

               <!--title and subtitle--
               <div class="post-description"> 
                  <div class="title h3">
                     {{post.title}}
                  </div>
                  <div class="title h5">
                     <p>{{post.subtitle}}</p>
                  </div>
               </div>

               {% if post.content %}
               <!--article media--
               <div class="post-image">
                  <img src="{{post.content.url}}" class="image" alt="image post">
               </div>
               {% endif %}
               
               <div class="post-description">
                  <div class="title h5">
                     <p align="justify">{{post.text}}</p>
                  </div>
                  <!-- likes and reposts --
                  <div class="stats">
                     <a href="#" class="btn btn-default stat-item"><i class="fa fa-thumbs-up icon"></i>{{likes.count}}</a>
                     <a href="#" class="btn btn-default stat-item"><i class="fa fa-share icon"></i>128</a>
                 </div>
               </div>

               <div class="post-footer">

                  <!--comments fields-->
                  {% if request.user.is_authenticated%}
                  <form class="input-group" method="POST">
                     {% csrf_token %}
                     {{ form.as_p }}
                     <span class="input-group-addon">
                     <button type="submit">
                        <a href="#"><i class="fa fa-edit"></i></a>  
                     </button>
                     </span>
                  </form>
                  {% endif %}

                  <!--comments--
                  <ul class="comments-list">

                     {% for c in comments %}

                     <li class="comment">
                        <a class="pull-left" href="{% url 'user-page' c.author.userslug %}">
                           <img class="avatar" src="{{c.author.userpic.url}}" alt="userpic">
                        </a>
                        <div class="comment-body">
                           <div class="comment-heading">
                                 <a href="{% url 'user-page' c.author.userslug %}"><h4 class="user">{{c.author}}</h4></a>
                                 <a><h5 class="time">{{c.time_create}}</h5></a>
                           </div>
                           <p>{{c.text}}</p>
                        </div>
                     </li>

                     {% endfor %}

                  </ul>

               </div>
               
            </div>
         </div>
      </div>
   </div>
</div> -->
 {% endcomment %}

<section class="blog-post section-header-offset">
   <div class="blog-post-container container">
      <div class="blog-post-data">
         <h3 class="title blog-post-title">Is VR the future?</h3>
         <div class="article-data">
            <span>Dec 6th 2021</span>
            <span class="article-data-spacer"></span>
            <span>4 Min read</span>
         </div>
         <img src="#" alt="">
      </div>

      <div class="container">
         <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis eius possimus hic eligendi distinctio rerum incidunt, esse quasi eum molestiae ducimus ipsam quae, aliquid ullam placeat dolorum nulla vero. Quam? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sapiente repellat consequatur culpa, repudiandae aut dolores iusto. Rem natus soluta, dolores, ad deleniti, aut dolorem corrupti quasi amet unde delectus hic?
         </p>
           
         <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis eius possimus hic eligendi distinctio rerum incidunt, esse quasi eum molestiae ducimus ipsam quae, aliquid ullam placeat dolorum nulla vero. Quam? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero quod necessitatibus, aspernatur pariatur asperiores earum quas adipisci veritatis quidem facilis! Nihil veniam quaerat nulla possimus, asperiores vero voluptatum placeat. Eveniet!
         </p>

         <blockquote class="quote">
            <p><span><i class="ri-double-quotes-l"></i></span> Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia voluptates, laboriosam voluptatum quos non consequuntur nesciunt necessitatibus tempora quod inventore corporis rem nihil itaque, at provident minus aliquam veritatis. Labore?  <span><i class="ri-double-quotes-r"></i></span></p>
         </blockquote>
       
         <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis eius possimus hic eligendi distinctio rerum incidunt, esse quasi eum molestiae ducimus ipsam quae, aliquid ullam placeat dolorum nulla vero. Quam? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vero quod necessitatibus, aspernatur pariatur asperiores earum quas adipisci veritatis quidem facilis! Nihil veniam quaerat nulla possimus, asperiores vero voluptatum placeat. Eveniet!
         </p>

         <div class="author d-grid">
            <div class="author-image-box">
               <img src="#" alt="" class="article-image">
            </div>
            <div class="author-about">
               <h3 class="author-name">John Doe</h3>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eaque quis repellat rerum, possimus cumque dolor repellendus eligendi atque explicabo exercitationem id.</p>
                  <ul class="list social-media">
                     <li class="list-item">
                        <a href="#" class="list-link"><i class="ri-instagram-line"></i></a>
                     </li>
                     <li class="list-item">
                        <a href="#" class="list-link"><i class="ri-facebook-circle-line"></i></a>
                     </li>
                     <li class="list-item">
                        <a href="#" class="list-link"><i class="ri-twitter-line"></i></a>
                     </li>
                  </ul>
            </div>
         </div>
      </div>

      <p>ЛАЙКИ : {{likes.count}}</p>

      {% if request.user.is_authenticated%}
         <form class="input-group" method="POST" id="newcom">
         {% csrf_token %}
         {{ form.as_p }}
            <span class="input-group-addon">
               <button type="submit">
                  <a href="#"><i class="fa fa-edit"></i></a>  
               </button>
            </span>
         </form>
      {% endif %}


      {% recursetree comments  %}
      <a href="{% url 'user-page' node.author.userslug %}"><h4>{{node.author.username}}</h4></a>
      
      <a><h5>{{node.time_create}}</h5></a>
      <p>{{node.text}}</p>

      {% if request.user.is_authenticated%}
      <button type="submit" class="btn" onclick="openForm({{node.id}})">ответить</button> 
      <div class="form-popup" id="myForm_{{node.id}}">
      <form class="input-group" method="POST" id="answercom_{{node.id}}"> 
         {% csrf_token %}
         <textarea name="text" cols="61" rows="3" class="form-control" placeholder="Add your comment here" style="resize:none;" required=""></textarea>
         <select name="parent" id="id_parent_{{node.id}}">
            <option value="{{node.id}}" selected="">{{node.id}}</option>
          </select>
          <button type="submit">
            <a href="#"><i class="fa fa-edit"></i></a>  
         </button> 
      </form>
      <button type="submit" class="btn" onclick="closeForm({{node.id}})">закрыть</button>
      <br></br>
      </div>
      {% endif %}
      
      {% if not node.is_leaf_node %}
         {{children}}
      {% endif %}

      {% endrecursetree %}

   </div>
</section>

{% endblock %}

mainapp/templates/mainapp/dev.html
<!--section of the site containing development and IT content-->
{% extends 'mainapp/base.html' %}
{% load mainapp_tags %}

{% block content %}

{% include 'mainapp/list_articles.html' %}

{% endblock %}

mainapp/templates/mainapp/economy.html
<!--section of the site containing economic content-->
{% extends 'mainapp/base.html' %}
{% load mainapp_tags %}

{% block content %}

{% include 'mainapp/list_articles.html' %}

{% endblock %}

mainapp/templates/mainapp/email_password_reset.html
{% autoescape off %}

Hello!
Для изменения пароля от аккаунта перейдите по этой ссылке.
http://{{domain}}{% url 'userpasswordreset' uidb64=uid token=token %} 


{% endautoescape %}

mainapp/templates/mainapp/email_verify.html
{% autoescape off %}

Hello, {{ user.username }}!
Для завершения регистрации перейдите по ссылке:
http://{{domain}}{% url 'userverify' uidb64=uid token=token %} 


{% endautoescape %}

mainapp/templates/mainapp/error.html
{% extends 'mainapp/base.html' %}

<img src="{% static 'mainapp/images/404.png'%}"

mainapp/templates/mainapp/life.html
<!--section of the site containing life content-->
{% extends 'mainapp/base.html' %}
{% load mainapp_tags %}

{% block content %}

{% include 'mainapp/list_articles.html' %}

{% endblock %}

mainapp/templates/mainapp/list_articles.html
{% load static %}

<section id="blog">
  
  <!-- Articles Container -->
   
  <div class="articles-container">
    {% for p in posts %}
    <div class="article-box">
      
      <div class="article-img">
        {% if p.content%}
          <img src="{{p.content.url}}" alt="Article">
        {% endif %}
      </div>
      <div class="article-text">
        <span>{{p.time_create}} | <a href="{% url p.section %}">{{ p.get_section_display }}</a></span>
        <a href="{{ p.get_absolute_url }}" class="article-title">{{p.title}}</a>
        <p>{{p.subtitle}}</p>
        <a href="{{ p.get_absolute_url }}">Подробнее...</a>
      </div>    
    </div>
    {% endfor %}

  </div>
  
</section>

mainapp/templates/mainapp/p.html
<!--user page template-->
{% extends 'mainapp/base.html' %}
{% load static %} 

{% block content %}

<div class="container bootstrap snippets bootdey">
    <div class="row">
        <div class="panel">
            <div class="cover-photo">
                <div class="fb-timeline-img">
                    {% if thisuser.theme %}
                    <img src="{{ thisuser.theme.url }}" alt="user-page-background">
                    {% endif %}
                </div>
                <div class="fb-name">
                    <h2><a href="#">{{thisuser.username}}</a></h2>
                    {% if user == thisuser %}
                    {% endif %}
                </div>
            </div>
            <div class="panel-body">
                <div class="profile-thumb">
                    {% if thisuser.userpic %}
                    <img src="{{ thisuser.userpic.url }}" alt="userpic">
                    {% endif %}
                </div>

                <!--https://getbootstrap.com/docs/5.2/components/navs-tabs/-->
                <ul class="nav nav-pills">
                    <li class="nav-item">
                    <!--раздел по умолчанию-->
                    <!--в разделе статьи вывод стандартной модели из list_article -->
                      <a class="nav-link active" aria-current="page" href="#">Статьи</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Подписчики</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Комментарии</a>
                    </li>
                </ul>

            </div>
        </div>

        <div class="panel profile-info">
            <form>
                <textarea class="form-control input-lg p-text-area" rows="2" placeholder="Whats in your mind today?"></textarea>
            </form>
            <footer class="panel-footer">
                <ul class="nav nav-pills">
                    <li type="button" class="btn btn-info pull-right">Post</li>
                </ul>
            </footer>
        </div>
        
    </div>
</div>

{% endblock %}

mainapp/templates/mainapp/password_reset_confirm.html
{% extends 'mainapp/base.html' %}

{% block content %}
<form action="" method="post">
   {% csrf_token %}
   {{form.as_p}}
   <button type="submit">Изменить</button>
</form>
{% endblock %}

mainapp/templates/mainapp/psettings.html
{% extends 'mainapp/base.html' %}
{% load static %} 

{% block content %}

{% if request.user == thisuser %}
<h1> настройка вашего профиля {{thisuser.username}} </h1>

<form id="resetform2" method="POST" class="input-group" enctype="multipart/form-data">
   {% csrf_token %}
   {% for f in form %}
      <div id="response4" class="errors">{{f.errors}}</div>
      {{f.label}}{{f}}
   {% endfor %}
   <br><button type="submit" id="userupd">change</button></br>
</form>
<br></br>
<br></br>
<br></br>
<form id="resetpassword" method="POST" class="input-group">
   {% csrf_token %}
   <button type="submit" id="userupd">Изменить пароль</button>
</form>

{% else %}

<h1> Хорошие новости, мы не забыли проверку на право доступа в этом месте =/</h1>

{% endif %}

{% endblock %}

mainapp/templates/mainapp/register.html
{% extends 'mainapp/base.html' %}


{% block content %}

<form method="POST" class="input-group">
   {% csrf_token %}

   {% for f in form %}
      <p>{{f.label}}{{f}}</p>
      {{f.errors}}
   {% endfor %}

   <button type="submit">Sign up</button>
</form>
{% endblock %}